# Generated by Django 4.1.7 on 2023-08-09 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehiclehystory",
            name="owner_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="vehiclehystory",
            name="plate_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="vehiclehystory",
            name="vin_code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
