# Generated by Django 4.1.7 on 2023-09-22 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Events", "0002_vehiclehystory_owner_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehiclehystory",
            name="historical_note",
            field=models.CharField(
                choices=[
                    (
                        "The vehicle order has been forwarded to the factory.",
                        "The vehicle order has been forwarded to the factory.",
                    ),
                    (
                        "The vehicle is out of production.",
                        "The vehicle is out of production.",
                    ),
                    (
                        "The vehicle is ready for transport from the factory.",
                        "The vehicle is ready for transport from the factory.",
                    ),
                    (
                        "The vehicle arrived at the MOTOHOBI warehouse.",
                        "The vehicle arrived at the MOTOHOBI warehouse.",
                    ),
                    (
                        "The vehicle has been transferred to the dealer.",
                        "The vehicle has been transferred to the dealer.",
                    ),
                    (
                        "The vehicle is registered and issued with a reg number",
                        "The vehicle is registered and issued with a reg number",
                    ),
                    (
                        "The vehicle has been issued to the owner.",
                        "The vehicle has been issued to the owner.",
                    ),
                    ("", ""),
                ],
                max_length=150,
            ),
        ),
    ]
