# Generated by Django 4.1.7 on 2023-09-23 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0022_alter_factory_options"),
        ("Events", "0003_alter_vehiclehystory_historical_note"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehiclehystory",
            name="vehicle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="vehicles.vehicle",
            ),
        ),
    ]
