# Generated by Django 4.1.7 on 2023-08-10 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CFMOTO_Admin", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="approveadminvehicle",
            name="back_image",
            field=models.ImageField(blank=True, null=True, upload_to="vehicle_images/"),
        ),
        migrations.AddField(
            model_name="approveadminvehicle",
            name="front_image",
            field=models.ImageField(blank=True, null=True, upload_to="vehicle_images/"),
        ),
        migrations.AddField(
            model_name="approveadminvehicle",
            name="mileage",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="approveadminvehicle",
            name="vin_code",
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
    ]
