# Generated by Django 4.1.7 on 2023-08-10 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CFMOTO_Admin", "0002_approveadminvehicle_back_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="approveadminvehicle",
            name="mileage",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="approveadminvehicle",
            name="vin_code",
            field=models.CharField(max_length=17, null=True),
        ),
    ]
