# Generated by Django 4.1.7 on 2023-07-30 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0003_alter_deliveredvehicle_status'),
        ('dealers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receivedvehicle',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='importer.deliveredvehicle'),
        ),
    ]
