# Generated by Django 4.1.7 on 2023-07-30 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0002_alter_receivedvehicle_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivedvehicle',
            name='registration_number',
            field=models.CharField(max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='receivedvehicle',
            name='status',
            field=models.CharField(choices=[('PN', 'pending'), ('RC', 'received'), ('AR', 'Assign registration number')], default='PN', max_length=2),
        ),
        migrations.AlterField(
            model_name='receivedvehicle',
            name='vin_code',
            field=models.CharField(max_length=17, null=True),
        ),
    ]
