# Generated by Django 4.1.7 on 2023-07-30 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0003_receivedvehicle_registration_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('N', 'The vehicle has not  issued to the owner.'), ('y', 'The vehicle has been issued to the owner.')], default='RN', max_length=2)),
                ('received_vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealers.receivedvehicle')),
            ],
        ),
    ]
