# Generated by Django 4.1.7 on 2023-08-02 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0004_registeredvehicle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receivedvehicle',
            options={'verbose_name_plural': 'Received vehicles'},
        ),
    ]
