# Generated by Django 4.1.7 on 2023-09-19 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dealers", "0005_alter_receivedvehicle_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="registeredvehicle",
            name="received_vehicle",
        ),
        migrations.AddField(
            model_name="registeredvehicle",
            name="body_type",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="registeredvehicle",
            name="cargo_compartments",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="registeredvehicle",
            name="color",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="registeredvehicle",
            name="communication_terminal",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="registeredvehicle",
            name="country",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="registeredvehicle",
            name="date_of_manufacture",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="registeredvehicle",
            name="eu_type_approval",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="registeredvehicle",
            name="factory_name",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="registeredvehicle",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="product_images/"),
        ),
        migrations.AddField(
            model_name="registeredvehicle",
            name="lights",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="registeredvehicle",
            name="manufacture",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="registeredvehicle",
            name="model_name",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="registeredvehicle",
            name="orderer",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="registeredvehicle",
            name="orderer_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="registeredvehicle",
            name="orderer_phone",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="registeredvehicle",
            name="screen",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="registeredvehicle",
            name="series",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="registeredvehicle",
            name="sku",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="registeredvehicle",
            name="steering_power",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="registeredvehicle",
            name="vin_code",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="registeredvehicle",
            name="wheels",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="registeredvehicle",
            name="status",
            field=models.CharField(
                choices=[
                    ("N", "The vehicle has not been issued to the owner."),
                    ("y", "The vehicle has been issued to the owner."),
                ],
                default="RN",
                max_length=2,
            ),
        ),
    ]
