# Generated by Django 4.1.7 on 2023-09-19 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dealers", "0007_alter_registeredvehicle_model_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registeredvehicle",
            name="model_name",
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
