# Generated by Django 4.1.7 on 2023-09-22 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dealers", "0008_alter_registeredvehicle_model_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="registeredvehicle",
            name="vehicle_id",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
