# Generated by Django 4.1.7 on 2023-08-09 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleGarage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Manufacturer', models.CharField(blank=True, max_length=100, null=True)),
                ('series', models.CharField(blank=True, max_length=100, null=True)),
                ('Factory_name', models.CharField(blank=True, max_length=100, null=True)),
                ('model_name', models.CharField(blank=True, max_length=100, null=True)),
                ('eu_type', models.CharField(blank=True, max_length=100, null=True)),
                ('steering_power', models.CharField(blank=True, max_length=100, null=True)),
                ('wheels', models.CharField(blank=True, max_length=100, null=True)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('lights', models.CharField(blank=True, max_length=100, null=True)),
                ('screen', models.CharField(blank=True, max_length=100, null=True)),
                ('cargo_compartment', models.CharField(blank=True, max_length=100, null=True)),
                ('communication_terminal', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('sku', models.CharField(blank=True, max_length=100, null=True)),
                ('orderer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('orderer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('orderer_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('approved_by_admin', models.BooleanField(default=False, verbose_name='Approved by Admin')),
            ],
        ),
    ]
