# Generated by Django 4.1.7 on 2023-07-29 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0008_vehicle_orderer_email_vehicle_orderer_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveredVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_system_id', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('OW', 'On the way - Not received yet'), ('AW', 'Arrived at warehouse')], max_length=2)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicle')),
            ],
        ),
    ]
