# Generated by Django 4.1.7 on 2023-07-30 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0002_alter_deliveredvehicle_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveredvehicle',
            name='status',
            field=models.CharField(choices=[('OW', 'On the way - Not received yet'), ('AW', 'Arrived at warehouse'), ('TD', 'transfer to dealer')], max_length=2),
        ),
    ]
