# Generated by Django 4.1.7 on 2023-08-09 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Garage", "0002_rename_orderer_email_vehiclegarage_user_email_and_more"),
        ("importer", "0003_alter_deliveredvehicle_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfirmVehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("confirmation_date", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("approved", "Approved Vehicle for Garage"),
                            ("not_approved", "Not Approved Vehicle for Garage"),
                        ],
                        default="not_approved",
                        max_length=20,
                    ),
                ),
                (
                    "vehicle_garage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Garage.vehiclegarage",
                    ),
                ),
            ],
        ),
    ]
