# Generated by Django 4.1.7 on 2023-07-28 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_alter_vehicle_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='image',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='subcategory',
        ),
    ]
