# Generated by Django 4.1.7 on 2023-07-29 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_vehiclehystory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='vehiclehystory',
        ),
    ]
