# Generated by Django 4.1.7 on 2023-08-02 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0009_alter_lights_options_alter_series_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='steeringpower',
            options={'verbose_name_plural': 'Steering Power'},
        ),
        migrations.AddField(
            model_name='vehicle',
            name='Manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicles.manufacturer'),
        ),
    ]
