# Generated by Django 4.1.7 on 2023-08-03 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0012_remove_vehicle_image_remove_vehicle_subcategory_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vehicle",
            old_name="eu_type_approval",
            new_name="eu_type",
        ),
    ]
