# Generated by Django 4.1.7 on 2023-08-05 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0013_rename_eu_type_approval_vehicle_eu_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="cargocompartment",
            name="category",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="CargoCompartment_category",
                to="vehicles.category",
            ),
        ),
        migrations.AddField(
            model_name="color",
            name="category",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Color_category",
                to="vehicles.category",
            ),
        ),
        migrations.AddField(
            model_name="communicationterminal",
            name="category",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="CommunicationTerminal_category",
                to="vehicles.category",
            ),
        ),
        migrations.AddField(
            model_name="eutypeapproval",
            name="category",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="EUTypeApproval_category",
                to="vehicles.category",
            ),
        ),
        migrations.AddField(
            model_name="modelname",
            name="category",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ModelName_category",
                to="vehicles.category",
            ),
        ),
        migrations.AddField(
            model_name="screen",
            name="category",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Screen_category",
                to="vehicles.category",
            ),
        ),
        migrations.AddField(
            model_name="sku",
            name="category",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="SKU_category",
                to="vehicles.category",
            ),
        ),
        migrations.AddField(
            model_name="steeringpower",
            name="category",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="SteeringPower_category",
                to="vehicles.category",
            ),
        ),
        migrations.AddField(
            model_name="wheels",
            name="category",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Wheels_category",
                to="vehicles.category",
            ),
        ),
    ]
