# Generated by Django 4.1.7 on 2023-08-05 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0014_cargocompartment_category_color_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="factory",
            name="category",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Factory_category",
                to="vehicles.category",
            ),
        ),
    ]
