# Generated by Django 4.1.7 on 2023-08-05 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0015_factory_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="factory",
            options={"verbose_name_plural": "Factory name"},
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="series",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="vehicles.category",
            ),
        ),
    ]
