# Generated by Django 4.1.7 on 2023-08-09 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0016_alter_factory_options_alter_vehicle_series"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="factory",
            options={},
        ),
        migrations.AddField(
            model_name="eutypeapproval",
            name="factory_name",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Factory_eutype",
                to="vehicles.factory",
            ),
        ),
        migrations.AddField(
            model_name="modelname",
            name="factory_name",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Factory_modelname",
                to="vehicles.factory",
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="series",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="vehicles.series",
            ),
        ),
    ]
