# Generated by Django 4.1.7 on 2023-08-09 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0017_alter_factory_options_eutypeapproval_factory_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="modelname",
            name="factory_name",
        ),
    ]
