# Generated by Django 4.1.7 on 2023-08-09 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0021_remove_eutypeapproval_factory_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="factory",
            options={"verbose_name_plural": "Factory name"},
        ),
    ]
