# Generated by Django 4.1.7 on 2023-07-30 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0002_alter_newreceivedvehicle_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='newreceivedvehicle',
        ),
    ]
