# Generated by Django 4.1.7 on 2023-10-18 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_subcategory"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sku", models.CharField(blank=True, max_length=50)),
                ("vin_code", models.CharField(blank=True, max_length=50)),
                (
                    "manufacture",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                ("series", models.CharField(blank=True, max_length=100, null=True)),
                ("model_name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "factory_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("color", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "eu_type_approval",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("body_type", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "steering_power",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("wheels", models.CharField(blank=True, max_length=50, null=True)),
                ("screen", models.CharField(blank=True, max_length=50, null=True)),
                ("lights", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "cargo_compartments",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "communication_terminal",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("date_of_manufacture", models.DateField(blank=True, null=True)),
                ("orderer", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "orderer_phone",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "orderer_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("importer", models.CharField(blank=True, max_length=100, null=True)),
                ("dealer", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="product_images/"
                    ),
                ),
                ("public_id", models.IntegerField(null=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="products.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registered vehicles",
                "verbose_name_plural": "Registered vehicles",
            },
        ),
    ]
