# Generated by Django 4.1.7 on 2023-10-18 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_newsparepart"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mileage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Mileage", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Year",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Year", models.CharField(max_length=255)),
            ],
        ),
    ]
