# Generated by Django 4.1.7 on 2023-10-18 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_mileage_year"),
    ]

    operations = [
        migrations.CreateModel(
            name="Maintainencepoint",
            fields=[
                (
                    "Point_id",
                    models.AutoField(db_column="id", primary_key=True, serialize=False),
                ),
                ("Maintainencepoint_name", models.TextField(blank=True, null=True)),
                ("instructions", models.TextField(blank=True, null=True)),
                ("instruction_active", models.BooleanField(default=False)),
                ("fill_active", models.BooleanField(default=False)),
                ("value_active", models.BooleanField(default=False)),
                (
                    "image_1",
                    models.ImageField(
                        blank=True, null=True, upload_to="service_images/"
                    ),
                ),
                (
                    "image_2",
                    models.ImageField(
                        blank=True, null=True, upload_to="service_images/"
                    ),
                ),
                (
                    "image_3",
                    models.ImageField(
                        blank=True, null=True, upload_to="service_images/"
                    ),
                ),
                (
                    "image_4",
                    models.ImageField(
                        blank=True, null=True, upload_to="service_images/"
                    ),
                ),
                ("video", models.URLField(blank=True, null=True)),
                ("my_order", models.PositiveIntegerField(db_index=True, default=0)),
            ],
            options={
                "verbose_name_plural": "Maintenance points",
                "ordering": ["my_order"],
            },
        ),
    ]
