# Generated by Django 4.1.7 on 2023-10-18 05:43

from django.db import migrations, models
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0022_alter_factory_options"),
        ("products", "0007_maintainencepoint"),
    ]

    operations = [
        migrations.CreateModel(
            name="Maintenance_List",
            fields=[
                (
                    "Maintenance_list_id",
                    models.AutoField(db_column="id", primary_key=True, serialize=False),
                ),
                ("Maintenance_list_name", models.CharField(max_length=100)),
                ("Maintainence_description", models.TextField(blank=True, null=True)),
                ("my_order", models.PositiveIntegerField(db_index=True, default=0)),
                ("Factory_name", models.ManyToManyField(to="vehicles.factory")),
                (
                    "Maintenance_List_Point_name",
                    sortedm2m.fields.SortedManyToManyField(
                        help_text=None,
                        sorted="my_order",
                        to="products.maintainencepoint",
                    ),
                ),
                ("Year", models.ManyToManyField(to="products.year")),
                ("mileage", models.ManyToManyField(to="products.mileage")),
            ],
        ),
    ]
