# Generated by Django 4.1.7 on 2023-10-18 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_maintenance_list"),
    ]

    operations = [
        migrations.AlterField(
            model_name="maintenance_list",
            name="Maintenance_List_Point_name",
            field=models.ManyToManyField(to="products.maintainencepoint"),
        ),
    ]
