# Generated by Django 4.1.7 on 2023-10-18 05:45

from django.db import migrations
import sortedm2m.fields
from sortedm2m.operations import AlterSortedManyToManyField




class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_alter_maintenance_list_maintenance_list_point_name"),
    ]

    operations = [
        AlterSortedManyToManyField(
            model_name="maintenance_list",
            name="Maintenance_List_Point_name",
            field=sortedm2m.fields.SortedManyToManyField(
                help_text=None, sorted="my_order", to="products.maintainencepoint"
            ),
        ),
    ]
