# Generated by Django 4.1.7 on 2023-10-18 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0010_alter_maintenance_list_maintenance_list_point_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="maintenance_list",
            options={
                "ordering": ["my_order"],
                "verbose_name": "Maintenance List",
                "verbose_name_plural": "Maintenance Lists",
            },
        ),
    ]
