# Generated by Django 4.1.7 on 2023-10-20 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0014_warranty_repairing_checkwarranty"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="maintenance_list",
            options={
                "verbose_name": "Maintenance List",
                "verbose_name_plural": "Maintenance Lists",
            },
        ),
        migrations.RemoveField(
            model_name="maintenance_list",
            name="my_order",
        ),
    ]
