# Generated by Django 4.1.7 on 2023-10-22 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0015_alter_maintenance_list_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="maintainencepoint",
            old_name="video",
            new_name="video1",
        ),
        migrations.AddField(
            model_name="maintainencepoint",
            name="image_5",
            field=models.ImageField(blank=True, null=True, upload_to="service_images/"),
        ),
        migrations.AddField(
            model_name="maintainencepoint",
            name="video2",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="maintainencepoint",
            name="video3",
            field=models.URLField(blank=True, null=True),
        ),
    ]
