# Generated by Django 4.1.7 on 2023-10-24 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0022_alter_factory_options"),
        ("products", "0016_rename_video_maintainencepoint_video1_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vincode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vincode", models.CharField(max_length=17, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Bulletins",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bulletins_name", models.CharField(max_length=100)),
                ("bulletins_description", models.TextField()),
                ("pdf_instructions", models.FileField(upload_to="pdf_instructions/")),
                (
                    "factoryname",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vehicles.factory",
                    ),
                ),
                (
                    "series",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vehicles.series",
                    ),
                ),
                (
                    "vincode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.vincode",
                    ),
                ),
            ],
        ),
    ]
