# Generated by Django 4.1.7 on 2023-10-26 05:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0018_alter_bulletins_options_bulletins_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bulletins",
            name="Date",
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
