# Generated by Django 4.1.7 on 2023-10-31 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0012_remove_registeredvehicle_received_vehicle'),
        ('products', '0019_alter_bulletins_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mechanicalnote',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mechanical_notes', to='dealers.registeredvehicle'),
        ),
        migrations.AlterField(
            model_name='productservice',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='dealers.registeredvehicle'),
        ),
        migrations.AlterField(
            model_name='serviceimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealers.registeredvehicle'),
        ),
    ]
