# Generated by Django 4.1.7 on 2023-10-31 10:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_alter_mechanicalnote_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletins',
            name='years',
            field=models.ManyToManyField(blank=True, to='products.year'),
        ),
        migrations.AlterField(
            model_name='bulletins',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='bulletins',
            name='bulletins_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='bulletins',
            name='vincode',
            field=models.ManyToManyField(blank=True, to='products.vincode'),
        ),
    ]
