# Generated by Django 4.1.7 on 2023-11-04 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_alter_newsparepart_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warranty',
            name='Warranty_id',
            field=models.CharField(max_length=9, unique=True, verbose_name='Warranty ID'),
        ),
    ]
