# Generated by Django 4.1.7 on 2023-12-04 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0012_remove_registeredvehicle_received_vehicle'),
        ('products', '0024_bulletins_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='temporaryWarranty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mileage', models.PositiveIntegerField()),
                ('cause', models.TextField()),
                ('review', models.TextField()),
                ('remarks', models.TextField()),
                ('failure_description', models.TextField()),
                ('picture', models.ImageField(null=True, upload_to='maintenance/')),
                ('video', models.FileField(null=True, upload_to='maintenance/')),
                ('time', models.CharField(max_length=255, verbose_name='Time')),
                ('Warranty_id', models.CharField(max_length=9, unique=True, verbose_name='Warranty ID')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealers.registeredvehicle')),
                ('replace_parts', models.ManyToManyField(to='products.newsparepart')),
            ],
        ),
        migrations.CreateModel(
            name='temporaryRepairing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mileage', models.PositiveIntegerField()),
                ('customer_description', models.TextField()),
                ('receiver_description', models.TextField()),
                ('feedback', models.TextField()),
                ('picture', models.ImageField(null=True, upload_to='maintenance/')),
                ('video', models.FileField(null=True, upload_to='maintenance/')),
                ('time', models.CharField(max_length=255, verbose_name='Time')),
                ('repairing_id', models.CharField(max_length=9, unique=True, verbose_name='Repairing ID')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealers.registeredvehicle')),
                ('replace_parts', models.ManyToManyField(to='products.newsparepart')),
            ],
        ),
    ]
