# Generated by Django 4.1.7 on 2023-12-07 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0012_remove_registeredvehicle_received_vehicle'),
        ('products', '0027_temporarymaintenance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='temporarymaintenance',
            options={'verbose_name': 'temporary maintenance', 'verbose_name_plural': 'temporary maintenance'},
        ),
        migrations.CreateModel(
            name='TemporaryMechanicalNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('selected_mileage', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporary_mechanical_notes', to='dealers.registeredvehicle')),
            ],
        ),
    ]
