# Generated by Django 4.1.7 on 2023-12-07 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_alter_temporarymaintenance_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporarymaintenance',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
