# Generated by Django 4.1.7 on 2023-12-13 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_temporarymaintenance_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporarymechanicalnote',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='temporarymechanicalnote',
            name='selected_mileage',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='temporaryrepairing',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='maintenance/'),
        ),
        migrations.AlterField(
            model_name='temporaryrepairing',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='maintenance/'),
        ),
        migrations.AlterField(
            model_name='temporarywarranty',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='maintenance/'),
        ),
        migrations.AlterField(
            model_name='temporarywarranty',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='maintenance/'),
        ),
    ]
